name: test
on: [push]

permissions:
  contents: write  # ğŸ‘ˆ í•„ìˆ˜

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # ê°œì¸ í† í°ì„ ì‚¬ìš©í•  ê²ƒì¸ì§€ ë§ ê²ƒì¸ì§€
        persist-credentials: false 
    - name: 1. pip ì—…ê·¸ë˜ì´ë“œ
      run: python -m pip install --upgrade pip
    - name: 2. í™˜ê²½ ì„¤ì •
      run: pip install -r requirements.txt
    - name: 3. íŒŒì´ì¬ ì‹¤í–‰
      run: python test.py
    - name: Commit files
      run: |
        git config --local user.email "fresh601@gmail.com"
        git config --local user.name "fresh601"
        git add .
        git commit -m "Run crawler and update current data"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        # branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
